raw_data:
  name: ./data/raw.csv
clean_data:
  name: ./data/clean.csv
  json: ./data/clean.json
  used_fields:
    - Title
    - Podficcer
    - Author
    - Ship
    - Link
  no_filter_fields:
    - Link
website:
  data: ./data/sheet.csv
  table_entries_per_page: 10
  autocomplete_max_length: 40
