raw_data:
  name: ./data/raw.csv
clean_data:
  name: ./data/phone_clean.csv
  json: ./data/phone_clean.json
  used_fields:
    - Title
    - Podcaster
    - Author
    - Status
    - Chapters
    - Time
    - Ship or Main Character
    - Link
    - Spotify/stream
    - Third Link
  link_fields:
    - Link
    - Spotify/stream
    - Third Link
  no_filter_fields:
    - Link
website:
  data: ./data/sheet.csv
  table_entries_per_page: 100
  autocomplete_max_length: 40
